language: node_js
node_js:
- 4.2.1
sudo: false
before_script:
- npm install -g gulp
before_deploy: gulp build
branches:
  except:
  - master
deploy:
  provider: releases
  api_key:
    secure: 05O2+fbQH6hLjOGnU8jqEF+WoBJ8oGqbCo1Ih0eVxwuVVfQugzQPntzxHlK3d/2P+qlA9Wnd68nxdXwYDqlos/8cDzhTXVJ6c5G6d1tfgjzoQxUYSA0AV/oZ6HxTU81+knwzwlBAB6/xbD8xA9Cpnoy+gcW3DoNuqUXE3IqgsrpBFqximCDzCuQ4xQ8ZMB69DuS3XKZcjgYZMfbPCQ/aw9hLJoFCFBa1k3JnJ7sj4M4dJeVcOcshTvU4FRKn0O15+8rEdzXMgub2BQ9Wh0v5Xr8KwwuKtBF9o3Lt3FKAxFbZrjZL7CPrZcvOuVbFQRAewetnzcDveZiwaDBCoNOCsr5Uq8vvIHc6PkA0z7EUAFH4mgbqLP8kONbRqbL8Xam2djmMBa/cAW/7jfrzqAUCWqWKV4vMfdNnPCSSM//sb+opJ2OlJDsRROxeZHHEjRyvoNie+04sG15LX2531IHPAdlFuKiaUt0CfiDEE5SDAIzCzoBJUpB2koxFnm8YR7ykHaMpQwDYjGE6KOD2SBg/OHzvcIbv98C9Vhkh3TKJAZset3sA+MpsVIicM5y/V5juBI/Lfqp4vBuVcaH+JHDIg8czVxSKPWUHjuv7qoFup9S4nUcc7trRmzdaEa7ksMVCIdlVP7Wu+DscJ7P2UnvWiv9YsM3z53xWQaw+H0hQ4xA=
  file_glob: true
  file:
    - dist/*.min.js
    - dist/*.html
  skip_cleanup: true
  on:
    tags: true
cache:
  directories:
  - node_modules
notifications:
  hipchat:
    rooms:
      secure: zsZ0x0mWt2ffzMPrKHvdu81eKbytVZbR04uS7L4fs+m6/f1Xr7nCDBoH3a3TVYIq7gkx/M/ce5nusHd65gc/RHiheBNJJDLSVjamuxWi2iHT5+11+H6Xa3WYGwgcoL1mWMahE3nZhO7aW8kwV7h7yIgq0VbU2IcCjwxP8zPtTSalXWHDPHgiMGZHA8SKbS2e065aDMaCNqfZR7txuwMpuFPfl2nFNeFKFK8PRsDgOqf0Pen855AnAkT3oeTtVWPSMnMQHfzfDtG6FpGA9QQiZZqLq5DQzz0Xo5AER7Y52tGaJPdRwINwObHYhYdCqM7MspGpXcc8FYCtB+YxDs0D3crzO+Dvl7vumunlpsl6iQDZCc9Cf/n7tZv9JkXMWFLblWYCpXeQxi2eojVff6C0n87Yj9qtCFqihI14hAR3j8fzfVGSrBS7TJIwDy9XPrdyyOfWEtTsM2OaXrvdOTQKk3eR6RDx8A8OqcMvHtN7VjAVQyArFELYq1ZyBjn95+e/F8LwT8LQ/PK9mYIgYrKs2auOwxHKCoff2LLbgkBUFaKWd5m1gaaq396cneTSB3LaoH/kU5gdsoO79CabrT2yfT0RcC+zHn+q1kOQfkoACvWSRhkppvr+sB7WQqi1scTucln//5LcMMkYbqhxk5lCi1Lu3JOJsevN1P4Z8M0yGL4=
